platform :ios, "8.0"

use_frameworks!

target 'sample-chat-swift' do
    
    pod 'Alamofire’
#pod 'QuickBlox'
#pod 'Quickblox-WebRTC'
    pod 'SVProgressHUD', '~> 1.1.3'
    
    #Production pod

    pod 'QMCVDevelopment', :git => 'https://github.com/QuickBlox/QMChatViewController-ios.git'

    #For development pods
    #pod 'QMCVDevelopment', :path => '../../QMChatViewController-ios/'
    
    #Production pod
    pod 'QMServicesDevelopment', :git => 'https://github.com/QuickBlox/q-municate-services-ios.git'
    
    #For development pods
    #pod 'QMServicesDevelopment', :path => '../../q-municate-services-ios/'
    
    pod 'SearchEmojiOnString'
    
    pod 'Fabric'
    pod 'Crashlytics'
    
end
